redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Owner\\Downloads\\FleetCommand-MultiVendor-Working-App-20260613-175042\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm install && npx expo export --platform web --output-dir dist"

[build.environment]
EXPO_PUBLIC_ENVIRONMENT = "production"
EXPO_PUBLIC_API_BASE_URL = "https://api.fleetmind.org"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]